
 // DATA
 const datastats = [
      {
        id: 1,
        Country: 'Slovakia, EU',
        Team: "HK 32 Liptovsky Mikulas",
        League: 'Extraliga',
        Years: '1999-2000',
        Seassons : 1,
        Games: 36,
        Goals:0,
        Assists:0,
        Points: 0, 
        img: '../hokejfoto/aces.png'
      },
      {
        id: 4,
        Country: 'Slovakia, EU',
        Team: "HK Dubnica",
        League: 'SHL',
        Years: '2001/2002',
        Seassons : 2,
        Games: 34,
        Goals:6,
        Assists:4,
        Points: 10,
        img: '../hokejfoto/DUBNICA.png'
      },
      {
        id: 3,
        Country: 'Slovakia, EU',
        Team: "HK 95 Povazska Bystrica",
        League: 'SHL',
        Years: '2006-2007',
        Seassons : 1,
        Games: 1,
        Goals:2,
        Assists:0,
        Points: 2,
        img: '../hokejfoto/rapid.png'
      },
      {
        id: 2,
        Country: 'Slovakia, EU',
        Team: "SHK 37 Piestany",
        League: 'SHL',
        Years: '2004-2005',
        Seassons : 1,
        Games: 3,
        Goals:0,
        Assists:0,
        Points: 0,
        img: '../hokejfoto/ALLSTAR.png'
      },
      {
        id: 5,
        Country: 'Slovakia, EU',
        Team: "HK Dukla Trencin",
        League: 'Extraliga',
        Years: '2001-2007',
        Seassons : 6,
        Games: 254,
        Goals:39,
        Assists:33,
        Points: 72,
        img: '../hokejfoto/tn.png'
      },
      {
        id:6,
        Country: 'Slovakia, EU',
        Team: "MsHK Zilina",
        League: 'Extraliga',
        Years: '07-09, 11-12',
        Seassons : 3,
        Games: 162,
        Goals:60,
        Assists:64,
        Points: 124,
        img: '../hokejfoto/za.png'
      },
      {
        id: 7,
        Country: 'Slovakia, EU',
        Team: "HKM Zvolen",
        League: 'Extraliga',
        Years: '2008-2009',
        Seassons : 1,
        Games: 21,
        Goals:6,
        Assists:6,
        Points: 12,
        img: '../hokejfoto/alaska.png'
      },
      {
        id: 8,
        Country: 'Czech Republic, EU',
        Team: "PSG Zlin",
        League: 'Extraliga',
        Years: '2009-2011',
        Seassons : 2,
        Games: 107,
        Goals:4,
        Assists:18,
        Points: 22,
        img: '../hokejfoto/zlin.png'
      },
      {
        id: 9,
        Country: 'California, USA',
        Team: "San Francisco Bulls",
        League: 'ECHL',
        Years: '2012-2013',
        Seassons : 1,
        Games: 67,
        Goals:34,
        Assists:25,
        Points: 59,
        img: '../hokejfoto/sanfran.png'
      },
      {
        id: 15,
        Country: 'USA / Florida',
        Team: "Orlando Solar Bears",
        League: 'ECHL',
        Years: '2014-2015',
        Seassons : 1,
        Games: 25,
        Goals:5,
        Assists:15,
        Points: 20,
        img: '../hokejfoto/orlando.png'
      },
      {
        id: 10,
        Country: 'Massachusetts, USA',
        Team: "Worchester Sharks",
        League: 'AHL',
        Years: '2012-2013',
        Seassons : 1,
        Games: 9,
        Goals:4,
        Assists:1,
        Points: 5,
        img: '../hokejfoto/sharks.png'
      },
      {
        id: 11,
        Country: 'Alaska, USA',
        Team: "Alaska Aces",
        League: 'ECHL',
        Years: '13-14, 15-17',
        Seassons : 3,
        Games: 181,
        Goals:91,
        Assists:121,
        Points: 212,
        img: '../hokejfoto/alaskacupp.png'
      },
      {
        id: 12,
        Country: 'Canada',
        Team: "Abbotsford Heat",
        League: 'AHL',
        Years: '2013-2014',
        Seassons : 1,
        Games: 3,
        Goals:0,
        Assists:0,
        Points: 0,
        img: '../hokejfoto/abots.png'
      },
      {
        id: 13,
        Country: 'California, USA',
        Team: "Stockton Thunder",
        League: 'ECHL',
        Years: '2014-2015',
        Seassons : 1,
        Games: 29,
        Goals:10,
        Assists:16,
        Points: 26,
        img: '../hokejfoto/stockton.png'
      },
      {  
        id: 14,   
        Country: 'Connecticut, USA',
        Team: "Bridgeport Sound Tigers",
        League: 'AHL',
        Years: '2014-2015',
        Seassons : 1,
        Games: 6,
        Goals:1,
        Assists:0,
        Points: 1,
        img: '../hokejfoto/bridgeport.png'
      },
      {
        id: 17,
        Country: 'Indiana, USA',
        Team: "Fort Wayne Komets",
        League: 'ECHL',
        Years: '2015-2016',
        Seassons : 1,
        Games: 10,
        Goals:2,
        Assists:6,
        Points: 8,
        img: '../hokejfoto/ala.png'
      },
      ,
      {
        id: 16,
        Country: 'Utah, USA',
        Team: "Utah Grizzlies",
        League: 'ECHL',
        Years: '2017-2018',
        Seassons : 1,
        Games: 4,
        Goals:0,
        Assists:1,
        Points: 1,
        img: '../hokejfoto/modalBG.png'
      },
      {
        id: 18,
        Country: 'South Dakota, USA',
        Team: "Rapid City Rush",
        League: 'ECHL',
        Years: '2017-2018',
        Seassons : 1,
        Games: 58,
        Goals:26,
        Assists:34,
        Points: 60,
        img: '../hokejfoto/repid.png'
      },
      {
        id: 19,
        Country: 'Oklahoma, USA',
        Team: "Tulsa Oilers",
        League: 'ECHL',
        Years: '2018-2019',
        Seassons : 1,
        Games: 10,
        Goals:5,
        Assists:3,
        Points: 8,
        img: '../hokejfoto/tulsa.png'
      },
      {
        id: 20,
        Country: 'California, USA',
        Team: "San Diego Gulls",
        League: 'AHL',
        Years: '2018-2019',
        Seassons : 1,
        Games: 1,
        Goals:0,
        Assists:0,
        Points: 0,
        img: '../hokejfoto/ABBOTSF.png'
      }
    ]

 export default datastats   